spring.application.name=dynamic-props-loader

# spring.datasource.url=jdbc:postgresql://localhost:5432/billadmin
# spring.datasource.username=admin
# spring.datasource.password=@dm!n
spring.datasource.url=jdbc:mysql://localhost:3306/feeo
spring.datasource.username=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.password=Pass.word123

# Temp
spring.jpa.hibernate.ddl-auto=create
